title: Kommunikation
team_tag_type: dark
filter_category: management
updated_by: 7d709850-5c35-4065-be68-b627c348051d
updated_at: 1657807933
blueprint: team_tags
localizations:
  en:
    title: 'communications and project assitance'
    slug: kommunikation-und-projektassistenz
    updated_by: f6128d7d-0471-44e5-b89a-e3213d7a0925
    updated_at: 1657210693
