title: 'Vertretung künstlerische Leitung'
team_tag_type: dark
filter_category: management
updated_by: f6128d7d-0471-44e5-b89a-e3213d7a0925
updated_at: 1657210983
blueprint: team_tags
localizations:
  en:
    title: 'Artistic Direction Substitute'
    slug: vertretung-kuenstlerische-leitung
    updated_by: f6128d7d-0471-44e5-b89a-e3213d7a0925
    updated_at: 1657210997
