title: 'Künstlerischer Beirat'
updated_by: f6128d7d-0471-44e5-b89a-e3213d7a0925
updated_at: 1670952223
blueprint: personen_funktionen
localizations:
  en:
    title: 'Artistic Board'
    slug: kuenstlerischer-beirat
    updated_by: f6128d7d-0471-44e5-b89a-e3213d7a0925
    updated_at: 1670952236
